name: Build and Test on Windows

on:
  push:
    branches:
      - add-Windows-build-action
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run build script
      run: python build.py

    - name: Run tests
      run: python -m unittest discover